Add header component
azrv/bakaexpress pull request #1
Opened 2021-05-17 19:25 UTC by greenwookez

I've added an adaptive and responsive Header component using grid and media queries.
Header contains logo and UserBar component which stands for login and shopping cart buttons.
There're 2 media queries breakpoints so the max-width<767 stands for phones and tablets, the max-width<992 stands for large tablets and small laptops.
Here are some visual representations of the results:
Desktops:
![image](https://user-images.githubusercontent.com/40858992/118544747-69840280-b75e-11eb-8088-637923ca0668.png)
Tablets:
![image](https://user-images.githubusercontent.com/40858992/118544953-a4863600-b75e-11eb-8d47-61625023613a.png)
iPhone X:
![image](https://user-images.githubusercontent.com/40858992/118544975-af40cb00-b75e-11eb-8c86-c65d48bb002a.png)
iPhone 6/7/8 Plus:
![image](https://user-images.githubusercontent.com/40858992/118545010-bc5dba00-b75e-11eb-92bd-20070da765f3.png)
iPhone 5/SE:
![image](https://user-images.githubusercontent.com/40858992/118545044-c54e8b80-b75e-11eb-929e-3deb9d72abcf.png)

2021-05-17 20:27 UTC, azrv requested changes

2021-05-17 20:27 UTC, azrv commented on public/index.html
> +    </style>
Please put to index.css

2021-05-17 20:27 UTC, azrv commented on public/index.html
> +      * {
html body

2021-05-17 20:27 UTC, azrv commented on src/components/Header/UserBar/UserBar.module.css
> +}
move to header.css

2021-05-17 20:27 UTC, azrv commented on src/components/Header/Header.jsx
> +          <img src={logo} alt='' />
alt='logo'

2021-05-17 20:27 UTC, azrv commented on src/components/Header/UserBar/UserBar.jsx
> +        <IoPersonCircle size={width <= 768 ? '30px' : '28px'} />
Move to media-query

2021-05-17 20:27 UTC, azrv commented on src/components/Header/UserBar/UserBar.jsx
> +        <IoCartOutline size={width <= 768 ? '30px' : '28px'} />
same

2021-05-17 20:27 UTC, azrv commented on src/components/Header/UserBar/UserBar.module.css
> +  display: flex;
Try to remove

2021-05-17 20:27 UTC, azrv commented on src/components/Header/UserBar/UserBar.module.css
> +  text-decoration: none;
normalize in index.css

2021-05-17 20:27 UTC, azrv commented on src/components/Header/UserBar/UserBar.module.css
> +}
Normalize in index.css

2021-05-18 15:17 UTC, greenwookez commented on src/components/Header/UserBar/UserBar.module.css
> +}
@azrv there is no way to pass .userbar class that was implemented in Header.module.css due to pecualrity of module.css dependency. The thing is that when you import a styles object from ./styles.module.css you actually get an object like:

{
  class_name1: "<Component>__<class_name1>__<SomeID>",
  class_name2: "<Component>__<class_name2>__<SomeID>",
  ...
}

So as you can see it contains strings and nothing more and the bundler automatically generates and links css files under the hood. So if you pass the <Component>__<class_name2>__<SomeID> string to the children component it won't work because there the children component is not actually connected to these styles.

Thats why I decided to move <nav className=".userBar"> tag to the Header component and that's it.

2021-05-18 15:35 UTC, azrv approved these changes

2021-05-18 15:35 UTC, merged